### ISSUE TITLE
Issue with the project

### ISSUE THREAD

**Issue by tommibru** [3KUdelta/TapeCounter_Revox_B77#1]
Hello there, we have just tried my dad an I to replicate the system exactly and we aren't being able to get anything to display on the oled. 

But when uploading a scratch from the SSD1306 the screen works. 

We have tried to troubleshoot but we couldn't get anywhere so far.

Any idea what it could be?

Thanks
-T

**Comment by 3KUdelta** [comment]
This seems to me like a library problem. Please make sure that you are using exactly this library: 
name=SSD1306Ascii
version=1.3.5
author=Bill Greiman <fat16lib@sbcglobal.net>
maintainer=Bill Greiman <fat16lib@sbcglobal.net>
sentence=Text display on small monochrome OLED modules.
paragraph=A basic SSD1306 text only library optimized for minimum memory usage.
category=Display
url=https://github.com/greiman/SSD1306Ascii


Best, Marc

**Comment by tommibru** [comment]
Hello Mark,

Thanks for the prompt answer. I did confirm that we are using the same exact version. 

As of now we are still not able to get it running but still trying to troubleshoot it. 

I also noticed that the sketch includes the file tapecounter_21x32.h but it's not included with the files. And I didn't find it either on the original project page.

-T

**Comment by 3KUdelta** [comment]
Hi, the file has been uploaded. It would be helpful if you upload your compilation error messages. 
Best, Marc

**Comment by tommibru** [comment]
I don't get any compilation errors. From what I can tell the sketch is uploaded correctly.

I will upload with the new file now and test. 

-T

**Comment by tommibru** [comment]
I tried and no luck, but looking at your images I just realized our display has GND VCC SCL(yours had SDK) SDA

I'm wondering now if that is the issue.

-T

**Comment by 3KUdelta** [comment]
#define I2C_ADDRESS 0x3C      // I2C display address (0x3C/0x3D, depending on display type)

It could be that your display is using a different address - try using 0x3D. Or if this does not work use an example code to scan your device address for I2C in order to find the correct address of your display.

Else: With a NANO SCL must be connected to A5 and SDA must be A4.

Marc

**Comment by tommibru** [comment]
I just used a scanner sketch and confirming it is 0x3C.

**Comment by 3KUdelta** [comment]
Try from scratch using example code HelloWorldWire.

**Comment by tommibru** [comment]
Uploaded the HelloWorldWire sketch.

On the photo is not really visible but its on the display top left very small font and quite unreadable. 

This is how it shows.
![image](https://github.com/user-attachments/assets/39f51710-be5c-4d08-8420-86e850dc572d)

**Comment by 3KUdelta** [comment]
That's good news. No try the same example but merge the settings from the TapeCounter.

**Comment by tommibru** [comment]
Good evening, we did figure it out. We had a batch of nanos that were causing the issue. I loaded on an uno and it worked. Then found an older nano and got it all up and running.

Thank you for the support sir!!

**Comment by 3KUdelta** [comment]
Happy to hear. Good luck with your project.
